language: python

cache:
  directories:
    - $HOME/nats-server

python:
  - "3.9"
  - "3.10"
  - "3.11"

before_install:
  - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
  - ./bin/task install-server-on-ci
  - pip install pipenv --upgrade
before_script:
  - export PATH=$HOME/nats-server:$PATH
script:
  - PIPENV_VERBOSITY=-1 ./bin/task ci

notifications:
  email: false

sudo: true
dist: focal

jobs:
  include:
    - name: "Python: 3.11/uvloop"
      python: "3.11"
      install:
        - pip install uvloop
  allow_failures:
    - python: "3.9"
    - name: "Python: 3.11/uvloop"
