language: python

cache:
  directories:
  - $HOME/nats-server

python:
  - "3.9"
  - "3.10"
  - "nightly"

before_install:
  - bash ./scripts/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

install:
  - pip install -e .[nkeys]

script:
  - make ci
  
notifications:
  email: false

sudo: true
dist: focal

jobs:
  include:
  - name: "Python: 3.11"
    python: "3.11"
    install:
      - pip install --upgrade pip
      - pip install aiohttp
  - name: "Python: 3.11/uvloop"
    python: "3.11"
    install:
      - pip install --upgrade pip
      - pip install uvloop
      - pip install aiohttp
  allow_failures:
    - name: "Python: 3.11"
    - name: "Python: 3.11/uvloop"
